# Generated by Django 3.2.4 on 2021-06-16 17:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 16, 17, 34, 15, 902873, tzinfo=utc), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='studiobooking',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 16, 17, 34, 15, 903434, tzinfo=utc), verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='studiobooking',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 16, 17, 34, 15, 903409, tzinfo=utc), verbose_name='start date'),
        ),
    ]
