# Generated by Django 3.2.4 on 2021-06-16 17:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210616_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiobooking',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='studiobooking',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 16, 17, 37, 0, 680454, tzinfo=utc), verbose_name='date created'),
        ),
    ]
