# Generated by Django 3.2.4 on 2021-06-29 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
