# Generated by Django 3.2.5 on 2021-07-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiobooking',
            name='band_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='studiobooking',
            name='first_name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='studiobooking',
            name='last_name',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
