# Generated by Django 3.2.5 on 2021-07-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20210709_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiobooking',
            name='end_date',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
