# Generated by Django 3.2.5 on 2021-07-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_studiobooking_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiobooking',
            name='booking_id',
            field=models.IntegerField(default=0),
        ),
    ]
