# Generated by Django 3.2.5 on 2021-07-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_studiobooking_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiobooking',
            name='booking_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
